export const teamnames = [
  // Ducks
  'Mighty Ducks',
  'Quack Attack',
  'Flying Mallards',
  'Duck Dynasty',
  'The Quackers',
  'Feather Force',
  'Duck & Cover',
  'The Splash Squad',
  'Waddle Warriors',
  'Pond Legends',
  'The Wingmen',
  'Quackstreet Boys',
  'Duckzilla',
  'The Beak Freaks',
  'The Floaters',
  'Air Ducks',
  'The Golden Geese',
  'Quack Panthers',
  'Quack Force One',
  'The Duckonauts',
  'Pond Pirates',
  'The Quack Pack',
  'Feathered Fury',

  // US Sports
  'Thunder Hawks',
  'Red Raptors',
  'Blue Barracudas',
  'Savage Wolves',
  'Firestorm',
  'Steel Titans',
  'Shadow Ninjas',
  'Ice Breakers',
  'Storm Riders',
  'Phantom Strikers',
  'Turbo Tornadoes',
  'Night Raiders',
  'Golden Griffins',
  'Blitz Brigade',
  'Crimson Crushers',
  'Neon Stallions',
  'Blackout Bears',
  'Velocity Vipers',
  'Atomic Rhinos',

  // Funny / Random
  'Die fliegenden Toaster',
  'Ultimate Chaos Crew',
  'Die Turnbeutelvergesser',
  'Glitch in the Matrix',
  'Die Gurkentruppe',
  'Ctrl Alt Elite',
  'The Snack Attack',
  'Die Laufenten',
  'Error 404 Team Not Found',
  'The Benchwarmers',
  'The Tryhards',
  'Die Untrainierten',
  'Almost Pros',
  'Die Afterwork Heroes',
  'Die Kaffeepausen Crew',
  'The Lag Spikes',
  'Die Sofa Athleten',
  'Panic! At The Disc',
  'Die Halbgaren',

  // Frisbee
  'Disc-o Inferno',
  'The Flying Discsasters',
  'Hucking Legends',
  'The Layout Kings',
  'Disc Devils',
  'The Huckaneers',
  'Air Traffic Control',
  'Spin Doctors',
  'The Backhand Bandits',
  'Forehand Fury',
  'The Disconauts',
  'Huck Yeah!',
  'The Skycatchers',
  'The Spin Wizards',
  'Endzone Artists',
]
